// Generated by gencpp from file tianbot_core/DebugCmdResponse.msg
// DO NOT EDIT!


#ifndef TIANBOT_CORE_MESSAGE_DEBUGCMDRESPONSE_H
#define TIANBOT_CORE_MESSAGE_DEBUGCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tianbot_core
{
template <class ContainerAllocator>
struct DebugCmdResponse_
{
  typedef DebugCmdResponse_<ContainerAllocator> Type;

  DebugCmdResponse_()
    : result()  {
    }
  DebugCmdResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DebugCmdResponse_

typedef ::tianbot_core::DebugCmdResponse_<std::allocator<void> > DebugCmdResponse;

typedef boost::shared_ptr< ::tianbot_core::DebugCmdResponse > DebugCmdResponsePtr;
typedef boost::shared_ptr< ::tianbot_core::DebugCmdResponse const> DebugCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tianbot_core::DebugCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tianbot_core::DebugCmdResponse_<ContainerAllocator1> & lhs, const ::tianbot_core::DebugCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tianbot_core::DebugCmdResponse_<ContainerAllocator1> & lhs, const ::tianbot_core::DebugCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tianbot_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::tianbot_core::DebugCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tianbot_core/DebugCmdResponse";
  }

  static const char* value(const ::tianbot_core::DebugCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::tianbot_core::DebugCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DebugCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tianbot_core::DebugCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tianbot_core::DebugCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIANBOT_CORE_MESSAGE_DEBUGCMDRESPONSE_H
