// Generated by gencpp from file tianbot_core/DebugCmdRequest.msg
// DO NOT EDIT!


#ifndef TIANBOT_CORE_MESSAGE_DEBUGCMDREQUEST_H
#define TIANBOT_CORE_MESSAGE_DEBUGCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tianbot_core
{
template <class ContainerAllocator>
struct DebugCmdRequest_
{
  typedef DebugCmdRequest_<ContainerAllocator> Type;

  DebugCmdRequest_()
    : cmd()  {
    }
  DebugCmdRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DebugCmdRequest_

typedef ::tianbot_core::DebugCmdRequest_<std::allocator<void> > DebugCmdRequest;

typedef boost::shared_ptr< ::tianbot_core::DebugCmdRequest > DebugCmdRequestPtr;
typedef boost::shared_ptr< ::tianbot_core::DebugCmdRequest const> DebugCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tianbot_core::DebugCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tianbot_core::DebugCmdRequest_<ContainerAllocator1> & lhs, const ::tianbot_core::DebugCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tianbot_core::DebugCmdRequest_<ContainerAllocator1> & lhs, const ::tianbot_core::DebugCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tianbot_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43a54fa49066cddcf148717d9d4a6353";
  }

  static const char* value(const ::tianbot_core::DebugCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43a54fa49066cddcULL;
  static const uint64_t static_value2 = 0xf148717d9d4a6353ULL;
};

template<class ContainerAllocator>
struct DataType< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tianbot_core/DebugCmdRequest";
  }

  static const char* value(const ::tianbot_core::DebugCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmd\n"
;
  }

  static const char* value(const ::tianbot_core::DebugCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DebugCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tianbot_core::DebugCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tianbot_core::DebugCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIANBOT_CORE_MESSAGE_DEBUGCMDREQUEST_H
