// Generated by gencpp from file tianbot_core/DebugCmd.msg
// DO NOT EDIT!


#ifndef TIANBOT_CORE_MESSAGE_DEBUGCMD_H
#define TIANBOT_CORE_MESSAGE_DEBUGCMD_H

#include <ros/service_traits.h>


#include <tianbot_core/DebugCmdRequest.h>
#include <tianbot_core/DebugCmdResponse.h>


namespace tianbot_core
{

struct DebugCmd
{

typedef DebugCmdRequest Request;
typedef DebugCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DebugCmd
} // namespace tianbot_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tianbot_core::DebugCmd > {
  static const char* value()
  {
    return "a34869486bf541f5f26e7eea27f4ece8";
  }

  static const char* value(const ::tianbot_core::DebugCmd&) { return value(); }
};

template<>
struct DataType< ::tianbot_core::DebugCmd > {
  static const char* value()
  {
    return "tianbot_core/DebugCmd";
  }

  static const char* value(const ::tianbot_core::DebugCmd&) { return value(); }
};


// service_traits::MD5Sum< ::tianbot_core::DebugCmdRequest> should match
// service_traits::MD5Sum< ::tianbot_core::DebugCmd >
template<>
struct MD5Sum< ::tianbot_core::DebugCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tianbot_core::DebugCmd >::value();
  }
  static const char* value(const ::tianbot_core::DebugCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tianbot_core::DebugCmdRequest> should match
// service_traits::DataType< ::tianbot_core::DebugCmd >
template<>
struct DataType< ::tianbot_core::DebugCmdRequest>
{
  static const char* value()
  {
    return DataType< ::tianbot_core::DebugCmd >::value();
  }
  static const char* value(const ::tianbot_core::DebugCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tianbot_core::DebugCmdResponse> should match
// service_traits::MD5Sum< ::tianbot_core::DebugCmd >
template<>
struct MD5Sum< ::tianbot_core::DebugCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tianbot_core::DebugCmd >::value();
  }
  static const char* value(const ::tianbot_core::DebugCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tianbot_core::DebugCmdResponse> should match
// service_traits::DataType< ::tianbot_core::DebugCmd >
template<>
struct DataType< ::tianbot_core::DebugCmdResponse>
{
  static const char* value()
  {
    return DataType< ::tianbot_core::DebugCmd >::value();
  }
  static const char* value(const ::tianbot_core::DebugCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIANBOT_CORE_MESSAGE_DEBUGCMD_H
